openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/admin/config:
    get:
      operationId: listgetconfigs
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/neo4j/export:
    get:
      operationId: listexportNeoDBs
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/neo4j/insert/{node_type}/{value}/:
    get:
      operationId: retrieveinsert
      description: ''
      parameters:
      - name: node_type
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: value
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/enrich/{enrich_type}/{value}/:
    get:
      operationId: retrieveenrichNode
      description: ''
      parameters:
      - name: enrich_type
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: value
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/delete/{node_id}/:
    get:
      operationId: retrievedelete
      description: ''
      parameters:
      - name: node_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/macroCybex/{query}/:
    get:
      operationId: retrievemacroCybex
      description: ''
      parameters:
      - name: query
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/macro/{subroutine}/:
    get:
      operationId: retrievemacro
      description: ''
      parameters:
      - name: subroutine
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/neo4j/wipe:
    get:
      operationId: listwipes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/getContents/{path}/:
    get:
      operationId: retrievegetContents
      description: ''
      parameters:
      - name: path
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/user_management/currentUserInfo/{info_to_return}/:
    get:
      operationId: retrievecurrentUserInfo
      description: Implements get method for currentUser API
      parameters:
      - name: info_to_return
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /isSignedIn:
    get:
      operationId: listisSignedIns
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - isSignedIn
  /isAdmin:
    get:
      operationId: listisAdmins
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - isAdmin
  /api/v1/enrich/{enrich_type}/:
    post:
      operationId: createenrichNodePost
      description: ''
      parameters:
      - name: enrich_type
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/enrichURL:
    post:
      operationId: createenrichURL
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/user_management/org_info:
    post:
      operationId: createorgInfo
      description: Implements post method for orgInfo API
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/user_management/org_add_remove:
    post:
      operationId: createorgAddRemoveUser
      description: Implements post method for orgInfo API
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /import_json:
    post:
      operationId: createimportJson
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - import-json
  /api/v1/position:
    post:
      operationId: createposition
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/dataEntry:
    post:
      operationId: createdataEntry
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/event/start:
    post:
      operationId: createstart
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/event/start/file:
    post:
      operationId: createstartFile
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
