openapi: 3.0.0
servers: []
info:
  description: This is a list of available routes exposed from the Cybex-P backend API Module. The Cybex-P API module is the gateway between the frontend web application/input modules and the backend Archive/Analytics modules.
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Cybex-P Query
    description: Operations for handling Report calls to the backend
  - name: Cybex-P Post
    description: Operations for the posting of data to the backend
  - name: Cybex-P Resource
    description: Resource operations are meant to handle miscellaneous task such as token authentication, system configurations, and appending of new users and organization
  - name: Cybex-P Ping
    description: Pinging protocols
paths:
  /query:
    get:
      tags:
        - Cybex-P Query
      summary: Makes an API report request to the backend
      operationId: query
      description: 'When called, a Cybex-P TDQL report request is made to the backend to check on the status of data that was provided by the user.'
      parameters: 
      - in: query
        name: 'Idnt_backend'
        schema:
          type: string
        description: 'Identity of the backend database where the API call is being made to'
      responses:
        '201':
          description: 'The report request is done processing and is ready to be returned to the user.'
        '202':
          description: 'The report request has been accepted. However, the data is still currently being processed. Proceed to query again at a later time.'
        '401':
          description: 'Unauthorized report request due to an invalid token.'
        '400':
          description: 'Bad request. The formatting of the query is invalid.'
        '500': 
          description: 'Internal error. The server is potentially down or another internal error is present'
  /raw:
    post:
      tags: 
        - Cybex-P Post
      summary: Post collected threat data and any user input to the raw module
      operationId: raw
      description: 'data that is called in with this URL are sent to the Cybex-P raw module to be validated for mandatory itypes and parsed into data that will be sent to the cache data lake.'
      parameters: []
      
      responses:
        '201':
          description: 'Succesful POST request. The file(s) has been uploaded successfully.'
        '400':
          description: 'Bad request. Inalid input, Incomplete input, or invalid raw input'
        '500': 
          description: 'Internal error. The Server itself has an error or the Cacde data lake is down'
  /ping:
    put:
      tags:
        - Cybex-P Ping
      summary: Simple ping to the specified identity backend
      operationId: ping
      description: 'A ping function to check up on the backend'
      parameters: []
      responses:
        '200':
          description: 'Ping to the backend was successfully made. The backend is alive and running'
  /TestToken:
    put:
      tags: 
        - Cybex-P Resource
      summary: Token validation endpoint
      operationId: token testing
      parameters: 
      - in: query
        name: 'Idnt_backend'
        schema:
          type: string
        description: 'Identity of the backend database where the API call is being made to'
      responses:
        '200':
          description: 'User token is valid'
        '401':
          description: 'Unauthorized. The provided token is invalid'
          
  /Create/Org:
    post:
      tags:
      -  Cybex-P Resource
      summary: Register a new organization in Cybex-P
      operationId: Register org
      parameters: []
      responses:
        '400':
          description: 'Bad request. The user who made the request is not an admin, the organization already exist, or a potential key error when trying to pull data from the request media.'
        '401':
          description: 'Attribute error, a request was made with a request attribute that is not a Cybex-P admin user'
        '201':
          description: 'Organization was successfully created in Cybex-P'
  /Create/User:
    post:
      tags:
      - Cybex-P Resource
      summary: Register a new user
      responses:
        '400':
          description: 'Bad request.The provided double validation for the password of the new user are not matching, the user already exist, or possible key error.'
        '401':
          description: 'Attribute error, the user context provided is not a Cybex-P admin and cannot create the user.'
        '201':
          description: 'the new user was successfully created in Cybex-P'
  /org/add/user:
    post:
      tags:
      -  Cybex-P Resource
      summary: Register a new user under an organization
      description: 'Add a new user or admin user under an organization in Cybex-P or add a new user to an access control list'
      responses:
        '400':
          description: 'Invalid org hash, the organization potentially does not exist; Key error; An invalid string is attempted to being added to the organization, or the user already exist in the provided organization or ACL'
        '401':
          description: 'a request was made by a user that is not an admin of the organization'
        '201':
          description: 'The user was successfully added to the access control list or organization.'
    
  /org/info:
    get:
      tags:
      -  Cybex-P Resource
      summary: Pull Organization information
      description: 'gets the admin and users of an organization and provides it to the client frontend'
      responses:
        '400':
          description: 'Invalid org hash, organization potentially does not exist. Invalid requested return type of the request media.'
        '401':
          description: 'a request was made by a user that is not an admin of the orgnization.'
        '201':
          description: 'a result was successfully extracted, see the result.'
  /org/del/user:
    delete:
      tags:
      -  Cybex-P Resource
      summary: Delete a user from an organization
      description: 'delete a user from an organization or access control list'
      responses:
        '400':
          description: 'Key error. Invalid org hash, '
  
  /org/admins_of:
    get:
      tags:
      -  Cybex-P Resource
      summary: Get the information of the current admins of an organization      
      responses:
        '400':
          description: 'Invalid token/authentication'
        '200':
          description: 'Successful authentication, see the result of admins of an organization provided from the endpoint'
  /orgs/user_of:
    get:
      tags:
      - Cybex-P Resource
      summary: Get information of all the users under an organization
      responses:
        '400':
          description: 'Invalid token/authentication'
        '200':
          description: 'Successful authentication, see the provided result of users of an organization provided from the endpoint'
  /user/info/self:
    get:
      tags:
      - Cybex-P Resource
      summary: Get information on the current sessions user
      responses:
        '400':  
          description: 'Invalid token/authentication'
        '200':
          description: 'Successful authentication, see the provided result of users of an organization provided from the endpoint'