# Generated by Django 3.0.7 on 2020-06-04 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cybexweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbport', models.CharField(blank=True, max_length=256, verbose_name='Database Port')),
                ('dbip', models.CharField(blank=True, max_length=256, verbose_name='Database IP')),
                ('dbuser', models.CharField(blank=True, max_length=256, verbose_name='Database User')),
                ('dbpass', models.CharField(blank=True, max_length=256, verbose_name='Database Pass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
