# Generated by Django 3.0.7 on 2020-06-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexweb', '0002_graphdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='graphdb',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
