# Generated by Django 3.0.7 on 2020-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdb',
            name='containerid',
            field=models.CharField(blank=True, max_length=256, verbose_name='Container ID'),
        ),
    ]
