# Generated by Django 3.1.2 on 2020-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexdata', '0002_graphdb_containerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cybex_token',
            field=models.CharField(blank=True, max_length=50, verbose_name='Timezone Name'),
        ),
    ]
