# Generated by Django 3.1.2 on 2020-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexdata', '0004_auto_20201114_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cybex_token',
            field=models.CharField(blank=True, max_length=300, verbose_name='CYBEX Token'),
        ),
    ]
