IOC:
  types:
    - IP
    - URL
    - Email
    - Domain
    - ASN
    - Host
    - Country
    - Subnet
    - Whois
    - Ports
    - Registrar
    - Nameserver
    - MailServer
    - Hash
    - User
    - Phone
    - BTC
    - MAC
    - BGPath
    - SSID
    - SPort
    - DPort


  enrichments:
    IP:
      - asn
      - gip
      - hostname
      - whois
      - cybexCount
      - cybexRelated
      - netblock
      - ports

    SPort:
      - none

    DPort:
      - none

    Email:
      - deconstructEmail
      - cybexRelated
      - cybexCount

    Host:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers
      - cybexRelated
      - cybexCount
      - pdns

    URL:
      - enrichURL
      - cybexRelated
      - cybexCount
    
    Domain:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers
      - cybexRelated
      - cybexCount

    Hash:
      - cybexRelated
      - cybexCount

    BTC:
      - cybexRelated
      - cybexCount

    ASN:
      - cybexRelated
      - cybexCount

    MAC:
      - none

    BGPath:
      - none

    SSID:
      - none
    
    Country:
      - none

    User:
      - none

    Subnet:
      - none

    Whois:
      - none

    Ports:
      - none

    Registrar: 
      - none

    Nameserver: 
      - none

    MailServer: 
      - none

    CybexCount:
      - none

    CybexRelated:
      - none

    Other:
      - none
